using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ReiEditor.Models.Resources.Client;
using ReiEditor.Models.Services.Assets.Scripting.Serialization;

namespace ReiEditor.Models.Services.Assets.Scripting;

public class BehaviourRegistrySourceGenerator
{
    private const string INCLUDE_FORMAT = "#include {0}";
        
    private readonly IResourceService _resourceService;
    private readonly ISerializableObjectsRegistry _serializableObjectsRegistry;

    public BehaviourRegistrySourceGenerator(IResourceService resourceService, ISerializableObjectsRegistry serializableObjectsRegistry)
    {
        _resourceService = resourceService;
        _serializableObjectsRegistry = serializableObjectsRegistry;
    }

    public Task GenerateBehaviourRegistrySourceFile(Dictionary<int, BehaviourAssetInfo> behaviours, IEnumerable<SerializableObjectInfo> serializableObjects)
    {
        var source = GetSourceText(behaviours, serializableObjects);
        return _resourceService.Write(source, _resourceService.GetProjectPath("Scripts", "Internal", "BehaviourRegistry.cpp"));
    }

    private string GetSourceText(Dictionary<int, BehaviourAssetInfo> behaviours, IEnumerable<SerializableObjectInfo> serializableObjects)
    {
        var serializableObjectInfos = serializableObjects.ToArray();
        
        var serializableObjectsAndBehaviours = new List<SerializableObjectInfo>();
        serializableObjectsAndBehaviours.AddRange(serializableObjectInfos);
        serializableObjectsAndBehaviours.AddRange(behaviours.Values);
        var assetRefTypes = GetAssetRefTemplateTypes(serializableObjectsAndBehaviours).ToArray();
        
        var str = new StringBuilder();

        str.AppendLine();
        str.AppendLine(GenerateWarning());
        str.AppendLine();
        
        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/EntityManagement/EntityManager.h>"));
        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/Behaviour/Behaviour.h>"));
        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/Assets/Core/AssetRefUtils.h>"));
        str.AppendLine();
        str.AppendLine(GenerateIncludes(serializableObjectsAndBehaviours));
        
        str.AppendLine(GenerateRegistryMethod(behaviours, assetRefTypes));

        str.AppendLine(GenerateSerializationImplementation(serializableObjectsAndBehaviours));
        str.AppendLine(GenerateDeserializationImplementation(serializableObjectsAndBehaviours));
        
        return str.ToString();
    }
    
    private string GenerateIncludes(IEnumerable<SerializableObjectInfo> objects)
    {
        var str = new StringBuilder();
        
        foreach (var obj in objects)
        {
            str.AppendLine(string.Format(INCLUDE_FORMAT, $"\"{obj.IncludePath}\""));
        }

        return str.ToString();
    }

    private string GenerateWarning()
    {
        var str = "// THIS CODE IS GENERATED BY REI ENGINE" +
                  "\n// ANY CHANGES TO THIS FILE WILL BE LOST";
        return str;
    }

    private string GenerateRegistryMethod(Dictionary<int, BehaviourAssetInfo> behaviours, IReadOnlyList<string> assetRefTypes)
    {
        var str = new StringBuilder();

        str.AppendLine("void ConfigureComponentsFactory(rei::BehaviourRegistry& f)");
        str.AppendLine("{");

        foreach (var assetRefType in assetRefTypes)
        {
            str.AppendLine($"    rei::assets::RegisterAutoAssignHandler<{assetRefType}>();");
        }
        
        if (assetRefTypes.Count > 0)
        {
            str.AppendLine();
        }
        
        foreach (var b in behaviours)
        {
            var behaviourNamespace = b.Value.Namespace;
            var behaviourName = b.Value.ObjectName;
            var behaviourId = b.Value.BehaviourId;
            var collectAssetDependenciesLambda = GenerateAssetDependenciesCollector(b.Value);

            str.AppendLine($"    f.RegisterComponent<{behaviourNamespace}::{behaviourName}>({behaviourId}, " +
                           $"[](const rei::ecs::Entity e) -> nlohmann::json " + "{ " +
                           $"auto& b = rei::GetInternalWorld()->GetRegistry()->Get<{behaviourNamespace}::{behaviourName}>(e); " +
                           $"b.BeforeREI_GET(); " +
                           $"return b.REI_GET();" + " }, " +
                           $"[](const rei::ecs::Entity e, const nlohmann::json& json) " + "{ " +
                           $"auto& b = rei::GetInternalWorld()->GetRegistry()->Get<{behaviourNamespace}::{behaviourName}>(e);" +
                           $"b.REI_SET(json); b.AfterREI_SET(); }}, " +
                           collectAssetDependenciesLambda +
                           ");");
        }
        
        str.AppendLine("}");

        return str.ToString();
    }

    private string GenerateDeserializationImplementation(IEnumerable<SerializableObjectInfo> objects)
    {
        var list = objects.ToList();
        
        var str = new StringBuilder();
        
        str.AppendLine("// --- REI_SET METHODS ---\n");
        
        foreach (var obj in list)
        {
            var objNamespace = obj.Namespace;
            var objectName = obj.ObjectName;
            
            var nameAndNamespace = objectName;
            if (!string.IsNullOrWhiteSpace(objNamespace)) nameAndNamespace = $"{objNamespace}::{objectName}";
            
            var serializedProperties = obj.SerializedProperties.ToList();

            if (obj.IsTemplate)
            {
                str.AppendLine("template <typename T>");
                str.AppendLine($"void {nameAndNamespace}<T>::REI_SET(const nlohmann::json& data)");
            }
            else
            {
                str.AppendLine($"void {nameAndNamespace}::REI_SET(const nlohmann::json& data)");
            }
            
            str.AppendLine("{");
            
            for (var index = 0; index < serializedProperties.Count; index++)
            {
                var p = serializedProperties[index];
                var isAssetRef = IsAssetRefProperty(p.Value);
                
                var propertyType = p.Value.SourceType;
                var indexOfTemplateStart = propertyType.IndexOf('<');
                if (indexOfTemplateStart != -1)
                {
                    propertyType = propertyType.Remove(indexOfTemplateStart, propertyType.Length - indexOfTemplateStart);
                }

                if (list.Exists(x =>
                    {
                        var objName = x.ObjectName;
                        indexOfTemplateStart = objName.IndexOf('<');
                        if (indexOfTemplateStart != -1)
                        {
                            objName = objName.Remove(indexOfTemplateStart, objName.Length - indexOfTemplateStart);
                        }

                        return objName == propertyType;
                    }))
                {
                    str.AppendLine($"    if (data.contains(\"{p.Key}\")) {p.Key}.REI_SET(data.at(\"{p.Key}\").at(\"Value\"));");
                }
                else
                {
                    str.AppendLine($"    if (data.contains(\"{p.Key}\")) {p.Key} = data.at(\"{p.Key}\").at(\"Value\");");
                }

                if (isAssetRef)
                {
                    str.AppendLine($"    if (data.contains(\"{p.Key}\")) rei::assets::SyncAfterExternalChange({p.Key});");
                }
            }
            
            str.AppendLine("}");
            
            str.AppendLine();
        }
        
        return str.ToString();
    }
    
    private string GenerateSerializationImplementation(IEnumerable<SerializableObjectInfo> objects)
    {
        var str = new StringBuilder();

        str.AppendLine("// --- REI_GET METHODS ---\n");
        
        var list = objects.ToList();
        
        foreach (var obj in list)
        {
            var objNamespace = obj.Namespace;
            var objectName = obj.ObjectName;
            
            var nameAndNamespace = objectName;
            if (!string.IsNullOrWhiteSpace(objNamespace)) nameAndNamespace = $"{objNamespace}::{objectName}";
            
            var serializedProperties = obj.SerializedProperties.ToList();

            if (obj.IsTemplate)
            {
                str.AppendLine("template <typename T>");
                str.AppendLine($"nlohmann::json {nameAndNamespace}<T>::REI_GET() const");
            }
            else
            {
                str.AppendLine($"nlohmann::json {nameAndNamespace}::REI_GET() const");
            }

            str.AppendLine("{");
            str.AppendLine("    return {");

            str.AppendLine("        {" + $"\"REI_TYPE\", \"{objectName}\"" + "},");
            
            for (var index = 0; index < serializedProperties.Count; index++)
            {
                var p = serializedProperties[index];
                
                var propertyType = p.Value.SourceType;
                var indexOfTemplateStart = propertyType.IndexOf('<');
                if (indexOfTemplateStart != -1)
                {
                    propertyType = propertyType.Remove(indexOfTemplateStart, propertyType.Length - indexOfTemplateStart);
                }

                var isEnum = _serializableObjectsRegistry.GetEnum(propertyType) != null;

                if (isEnum)
                {
                    str.AppendLine("        {" + $"\"{p.Key}\", (int) {p.Key}" + "},");
                }
                else if (list.Exists(x =>
                    {
                        var objName = x.ObjectName;
                        indexOfTemplateStart = objName.IndexOf('<');
                        if (indexOfTemplateStart != -1)
                        {
                            objName = objName.Remove(indexOfTemplateStart, objName.Length - indexOfTemplateStart);
                        }

                        return objName == propertyType;
                    }))
                {
                    str.AppendLine("        {" + $"\"{p.Key}\", {p.Key}.REI_GET()" + "},");
                }
                else
                {
                    str.AppendLine("        {" + $"\"{p.Key}\", {p.Key}" + "},");
                }
            }

            str.AppendLine("    };");
            str.AppendLine("}");

            str.AppendLine();
        }
        
        return str.ToString();
    }

    private static IEnumerable<string> GetAssetRefTemplateTypes(IEnumerable<SerializableObjectInfo> objects)
    {
        var result = new HashSet<string>();

        foreach (var obj in objects)
        {
            foreach (var property in obj.SerializedProperties.Values)
            {
                if (!IsAssetRefProperty(property, out var templateType)) continue;
                var qualifiedType = GetQualifiedTemplateType(templateType, obj.Namespace);
                result.Add(qualifiedType);
            }
        }

        return result;
    }
    
    private static bool IsAssetRefProperty(SerializableObjectInfo.SerializedPropertyData propertyData)
    {
        return IsAssetRefProperty(propertyData, out _);
    }

    private static bool IsAssetRefProperty(SerializableObjectInfo.SerializedPropertyData propertyData, out string templateType)
    {
        templateType = (GetTemplateTypeNameWithNamespace(propertyData.SourceType) ??
                        propertyData.TemplateTypeName ??
                        GetTemplateTypeName(propertyData.SourceType)) ?? string.Empty;
        if (string.IsNullOrWhiteSpace(templateType))
        {
            return false;
        }

        return GetSourceTypeBaseName(propertyData.SourceType) == "AssetRef";
    }

    private static string GetQualifiedTemplateType(string templateType, string objectNamespace)
    {
        if (templateType.Contains("::") || string.IsNullOrWhiteSpace(objectNamespace))
        {
            return templateType;
        }

        return $"{objectNamespace}::{templateType}";
    }

    private static string? GetTemplateTypeName(string type)
    {
        var startIndex = type.IndexOf('<');
        if (startIndex == -1) return null;

        var endIndex = type.LastIndexOf('>');
        if (endIndex == -1 || endIndex <= startIndex) return null;

        var templateType = type.Substring(startIndex + 1, endIndex - startIndex - 1);
        return templateType.Split("::").Last().Trim();
    }

    private static string? GetTemplateTypeNameWithNamespace(string type)
    {
        var startIndex = type.IndexOf('<');
        if (startIndex == -1) return null;

        var endIndex = type.LastIndexOf('>');
        if (endIndex == -1 || endIndex <= startIndex) return null;

        return type.Substring(startIndex + 1, endIndex - startIndex - 1).Trim();
    }

    private static string GetSourceTypeBaseName(string sourceType)
    {
        var templateStart = sourceType.IndexOf('<');
        var baseType = templateStart == -1 ? sourceType : sourceType.Substring(0, templateStart);
        return baseType.Split("::").Last().Trim();
    }

    private static string GenerateAssetDependenciesCollector(BehaviourAssetInfo behaviour)
    {
        var assetRefProperties = behaviour.SerializedProperties
            .Where(x => IsAssetRefProperty(x.Value, out _))
            .ToArray();

        if (assetRefProperties.Length == 0)
        {
            return "nullptr";
        }

        var str = new StringBuilder();
        str.Append("[](const nlohmann::json& data, std::vector<rei::assets::AssetDependency>& outDependencies) { ");

        foreach (var property in assetRefProperties)
        {
            var propertyName = property.Key;
            IsAssetRefProperty(property.Value, out var templateType);
            var qualifiedType = GetQualifiedTemplateType(templateType, behaviour.Namespace);

            str.Append($"if (data.contains(\"{propertyName}\")) {{ ");
            str.Append($"const auto& rawValue = data.at(\"{propertyName}\"); ");
            str.Append("const auto& assetRefValue = rawValue.contains(\"Value\") ? rawValue.at(\"Value\") : rawValue; ");
            str.Append("if (assetRefValue.contains(\"Id\")) { ");
            str.Append("const auto& rawId = assetRefValue.at(\"Id\"); ");
            str.Append("const auto& idValue = rawId.is_object() && rawId.contains(\"Value\") ? rawId.at(\"Value\") : rawId; ");
            str.Append("const std::string assetId = idValue.is_string() ? idValue.get<std::string>() : \"\"; ");
            str.Append("if (!assetId.empty()) { ");
            str.Append($"outDependencies.push_back(rei::assets::CreateTypedAssetDependency<{qualifiedType}>(assetId)); ");
            str.Append("} ");
            str.Append("} ");
            str.Append("} ");
        }

        str.Append("}");
        return str.ToString();
    }
}
