using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ReiEditor.Models.Resources.Client;
using ReiEditor.Models.Services.Assets.Scripting.Serialization;

namespace ReiEditor.Models.Services.Assets.Scripting;

public class BehaviourRegistrySourceGenerator
{
    private const string INCLUDE_FORMAT = "#include {0}";
        
    private readonly IResourceService _resourceService;

    public BehaviourRegistrySourceGenerator(IResourceService resourceService)
    {
        _resourceService = resourceService;
    }

    public Task GenerateBehaviourRegistrySourceFile(Dictionary<int, BehaviourAssetInfo> behaviours, IEnumerable<SerializableObjectInfo> serializableObjects)
    {
        var source = GetSourceText(behaviours, serializableObjects);
        return _resourceService.Write(source, _resourceService.GetProjectPath("Scripts", "Internal", "BehaviourRegistry.cpp"));
    }

    private string GetSourceText(Dictionary<int, BehaviourAssetInfo> behaviours, IEnumerable<SerializableObjectInfo> serializableObjects)
    {
        var serializableObjectInfos = serializableObjects.ToArray();
        
        var serializableObjectsAndBehaviours = new List<SerializableObjectInfo>();
        serializableObjectsAndBehaviours.AddRange(serializableObjectInfos);
        serializableObjectsAndBehaviours.AddRange(behaviours.Values);
        
        var str = new StringBuilder();

        str.AppendLine();
        str.AppendLine(GenerateWarning());
        str.AppendLine();
        
        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/EntityManagement/EntityManager.h>"));
        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/Behaviour/Behaviour.h>"));
        str.AppendLine();
        str.AppendLine(GenerateIncludes(serializableObjectsAndBehaviours));
        
        str.AppendLine(GenerateRegistryMethod(behaviours));

        str.AppendLine(GenerateSerializationImplementation(serializableObjectsAndBehaviours));
        str.AppendLine(GenerateDeserializationImplementation(serializableObjectsAndBehaviours));
        
        return str.ToString();
    }
    
    private string GenerateIncludes(IEnumerable<SerializableObjectInfo> objects)
    {
        var str = new StringBuilder();
        
        foreach (var obj in objects)
        {
            str.AppendLine(string.Format(INCLUDE_FORMAT, $"\"{obj.IncludePath}\""));
        }

        return str.ToString();
    }

    private string GenerateWarning()
    {
        var str = "// THIS CODE IS GENERATED BY REI ENGINE" +
                  "\n// ANY CHANGES TO THIS FILE WILL BE LOST";
        return str;
    }

    private string GenerateRegistryMethod(Dictionary<int, BehaviourAssetInfo> behaviours)
    {
        var str = new StringBuilder();

        str.AppendLine("void ConfigureComponentsFactory(rei::BehaviourRegistry& f)");
        str.AppendLine("{");
        
        foreach (var b in behaviours)
        {
            var behaviourNamespace = b.Value.Namespace;
            var behaviourName = b.Value.ObjectName;
            var behaviourId = b.Value.BehaviourId;

            str.AppendLine($"    f.RegisterComponent<{behaviourNamespace}::{behaviourName}>({behaviourId}, " +
                           $"[](const rei::ecs::Entity e) -> nlohmann::json " + "{" + $"return rei::GetInternalWorld().GetRegistry()->Get<{behaviourNamespace}::{behaviourName}>(e).REI_GET();" + " }, " +
                           $"[](const rei::ecs::Entity e, const nlohmann::json& json) " + "{" + $"rei::GetInternalWorld().GetRegistry()->Get<{behaviourNamespace}::{behaviourName}>(e).REI_SET(json); }});");
        }
        
        str.AppendLine("}");

        return str.ToString();
    }

    private string GenerateDeserializationImplementation(IEnumerable<SerializableObjectInfo> objects)
    {
        var list = objects.ToList();
        
        var str = new StringBuilder();
        
        str.AppendLine("// --- REI_SET METHODS ---\n");
        
        foreach (var obj in list)
        {
            var objNamespace = obj.Namespace;
            var objectName = obj.ObjectName;
            
            var nameAndNamespace = objectName;
            if (!string.IsNullOrWhiteSpace(objNamespace)) nameAndNamespace = $"{objNamespace}::{objectName}";
            
            var serializedProperties = obj.SerializedProperties.ToList();

            if (obj.IsTemplate)
            {
                str.AppendLine("template <typename T>");
                str.AppendLine($"void {nameAndNamespace}<T>::REI_SET(const nlohmann::json& data)");
            }
            else
            {
                str.AppendLine($"void {nameAndNamespace}::REI_SET(const nlohmann::json& data)");
            }
            
            str.AppendLine("{");
            
            for (var index = 0; index < serializedProperties.Count; index++)
            {
                var p = serializedProperties[index];
                
                var propertyType = p.Value.SourceType;
                var indexOfTemplateStart = propertyType.IndexOf('<');
                if (indexOfTemplateStart != -1)
                {
                    propertyType = propertyType.Remove(indexOfTemplateStart, propertyType.Length - indexOfTemplateStart);
                }

                if (list.Exists(x =>
                    {
                        var objName = x.ObjectName;
                        indexOfTemplateStart = objName.IndexOf('<');
                        if (indexOfTemplateStart != -1)
                        {
                            objName = objName.Remove(indexOfTemplateStart, objName.Length - indexOfTemplateStart);
                        }

                        return objName == propertyType;
                    }))
                {
                    str.AppendLine($"    if (data.contains(\"{p.Key}\")) {p.Key}.REI_SET(data.at(\"{p.Key}\").at(\"Value\"));");
                }
                else
                {
                    str.AppendLine($"    if (data.contains(\"{p.Key}\")) {p.Key} = data.at(\"{p.Key}\").at(\"Value\");");
                }
            }
            
            str.AppendLine("}");
            
            str.AppendLine();
        }
        
        return str.ToString();
    }
    
    private string GenerateSerializationImplementation(IEnumerable<SerializableObjectInfo> objects)
    {
        var str = new StringBuilder();

        str.AppendLine("// --- REI_GET METHODS ---\n");
        
        var list = objects.ToList();
        
        foreach (var obj in list)
        {
            var objNamespace = obj.Namespace;
            var objectName = obj.ObjectName;
            
            var nameAndNamespace = objectName;
            if (!string.IsNullOrWhiteSpace(objNamespace)) nameAndNamespace = $"{objNamespace}::{objectName}";
            
            var serializedProperties = obj.SerializedProperties.ToList();

            if (obj.IsTemplate)
            {
                str.AppendLine("template <typename T>");
                str.AppendLine($"nlohmann::json {nameAndNamespace}<T>::REI_GET() const");
            }
            else
            {
                str.AppendLine($"nlohmann::json {nameAndNamespace}::REI_GET() const");
            }

            str.AppendLine("{");
            str.AppendLine("    return {");

            str.AppendLine("        {" + $"\"REI_TYPE\", \"{objectName}\"" + "},");
            
            for (var index = 0; index < serializedProperties.Count; index++)
            {
                var p = serializedProperties[index];
                
                var propertyType = p.Value.SourceType;
                var indexOfTemplateStart = propertyType.IndexOf('<');
                if (indexOfTemplateStart != -1)
                {
                    propertyType = propertyType.Remove(indexOfTemplateStart, propertyType.Length - indexOfTemplateStart);
                }

                if (list.Exists(x =>
                    {
                        var objName = x.ObjectName;
                        indexOfTemplateStart = objName.IndexOf('<');
                        if (indexOfTemplateStart != -1)
                        {
                            objName = objName.Remove(indexOfTemplateStart, objName.Length - indexOfTemplateStart);
                        }

                        return objName == propertyType;
                    }))
                {
                    str.AppendLine("        {" + $"\"{p.Key}\", {p.Key}.REI_GET()" + "},");
                }
                else
                {
                    str.AppendLine("        {" + $"\"{p.Key}\", {p.Key}" + "},");
                }
            }

            str.AppendLine("    };");
            str.AppendLine("}");

            str.AppendLine();
        }
        
        return str.ToString();
    }
}