using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using ReiEditor.Models.Resources.Client;

namespace ReiEditor.Models.Services.Assets.Behaviours;

public class BehaviourRegistrySourceGenerator
{
    private readonly IResourceService _resourceService;

    public BehaviourRegistrySourceGenerator(IResourceService resourceService)
    {
        _resourceService = resourceService;
    }

    public Task GenerateBehaviourRegistrySourceFile(Dictionary<int, BehaviourAssetInfo> behaviours)
    {
        var source = GetSourceText(behaviours);
        return _resourceService.Write(source, _resourceService.GetProjectPath("Scripts", "Internal", "BehaviourRegistry.cpp"));
    }

    private string GetSourceText(Dictionary<int, BehaviourAssetInfo> behaviours)
    {
        var str = new StringBuilder();

        str.AppendLine();
        str.AppendLine(GenerateWarning());
        str.AppendLine();
        str.AppendLine(GenerateIncludes(behaviours));
        str.AppendLine(GenerateRegistryMethod(behaviours));
        str.AppendLine();
        str.AppendLine(GenerateBodyImplementation(behaviours));
        
        return str.ToString();
    }

    private string GenerateIncludes(Dictionary<int, BehaviourAssetInfo> behaviours)
    {
        const string INCLUDE_FORMAT = "#include {0}";

        var solutionPath = _resourceService.GetSolutionPath();
        var str = new StringBuilder();

        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/EntityManagement/EntityManager.h>"));
        str.AppendLine(string.Format(INCLUDE_FORMAT, "<Modules/Behaviour/Behaviour.h>"));
        str.AppendLine();
        
        foreach (var b in behaviours)
        {
            var fullPath = Path.GetFullPath(b.Value.Behaviour.FullPath);
            var headerInclude = fullPath.Replace(solutionPath, "");
            headerInclude = headerInclude.Replace("\\", "/");
            str.AppendLine(string.Format(INCLUDE_FORMAT, $"\"..{headerInclude}\""));
        }

        return str.ToString();
    }

    private string GenerateWarning()
    {
        var str = "// THIS CODE IS GENERATED BY REI ENGINE" +
                  "\n// ANY CHANGES TO THIS FILE WILL BE LOST";
        return str;
    }

    private string GenerateRegistryMethod(Dictionary<int, BehaviourAssetInfo> behaviours)
    {
        var str = new StringBuilder();

        str.AppendLine("void ConfigureComponentsFactory(rei::BehaviourRegistry& f)");
        str.AppendLine("{");
        
        foreach (var b in behaviours)
        {
            var behaviourName = b.Value.BehaviourName;
            var behaviourId = b.Value.BehaviourId;

            str.AppendLine($"    f.RegisterComponent<{behaviourName}>({behaviourId});");
        }
        
        str.AppendLine("}");

        return str.ToString();
    }

    private string GenerateBodyImplementation(Dictionary<int, BehaviourAssetInfo> behaviours)
    {
        var str = new StringBuilder();
        
        foreach (var b in behaviours)
        {
            var behaviourName = b.Value.BehaviourName;
            var serializedProperties = b.Value.SerializedProperties;

            str.AppendLine($"{behaviourName}::{behaviourName}(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)");
            str.AppendLine($"    : Behaviour(id, e)");
            foreach (var p in serializedProperties)
            {
                str.AppendLine($"    , {p.Key}(data.at(\"{p.Key}\").at(\"Value\"))");
            }
            str.AppendLine("{" + "}");
            str.AppendLine();
        }
        
        return str.ToString();
    }
}