
// THIS CODE IS GENERATED BY REI ENGINE
// ANY CHANGES TO THIS FILE WILL BE LOST

#include <Modules/EntityManagement/EntityManager.h>
#include <Modules/Behaviour/Behaviour.h>

#include "../Behaviours/MyBehaviour.h"

void ConfigureComponentsFactory(rei::BehaviourRegistry& f)
{
    f.RegisterComponent<MyBehaviour>(4);
}

MyBehaviour::MyBehaviour(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)
    : Behaviour(id, e)
    , _flag(data.at("_flag").at("Value"))
    , _counter(data.at("_counter").at("Value"))
    , _msg(data.at("_msg").at("Value"))
{}


