
// THIS CODE IS GENERATED BY REI ENGINE
// ANY CHANGES TO THIS FILE WILL BE LOST

#include <Modules/EntityManagement/EntityManager.h>
#include <Modules/Behaviour/Behaviour.h>

#include "C:\Repos\Rei\Rei\src\Common\Math\Vector3.h"
#include "C:\Repos\Rei\Rei\src\Modules\Render\Color\Color.h"

#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\Camera.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\MeshRenderer.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\transformation\Transform.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\light\AmbientLight.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\light\PointLight.h"

void ConfigureComponentsFactory(rei::BehaviourRegistry& f)
{
    f.RegisterComponent<rei::render::Camera>(0);
    f.RegisterComponent<rei::render::MeshRenderer>(1);
    f.RegisterComponent<rei::transformation::Transform>(2);
    f.RegisterComponent<rei::render::AmbientLight>(3);
    f.RegisterComponent<rei::behaviour::PointLight>(4);
}


rei::math::Vector3::Vector3(const nlohmann::json& data) :
    x(data.at("x").at("Value")),
    y(data.at("y").at("Value")),
    z(data.at("z").at("Value"))
{}

rei::render::Color::Color(const nlohmann::json& data) :
    r(data.at("r").at("Value")),
    g(data.at("g").at("Value")),
    b(data.at("b").at("Value")),
    a(data.at("a").at("Value"))
{}


rei::render::Camera::Camera(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)
    : Behaviour(id, e)
    , _fov(data.at("_fov").at("Value"))
    , _nearClipPlane(data.at("_nearClipPlane").at("Value"))
    , _farClipPlane(data.at("_farClipPlane").at("Value"))
{}

rei::render::MeshRenderer::MeshRenderer(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)
    : Behaviour(id, e)
{}

rei::transformation::Transform::Transform(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)
    : Behaviour(id, e)
    , _position(data.at("_position").at("Value"))
    , _rotation(data.at("_rotation").at("Value"))
    , _scale(data.at("_scale").at("Value"))
{}

rei::render::AmbientLight::AmbientLight(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)
    : Behaviour(id, e)
    , _strength(data.at("_strength").at("Value"))
    , _color(data.at("_color").at("Value"))
{}

rei::behaviour::PointLight::PointLight(const i32 id, const rei::ecs::Entity e, const nlohmann::json& data)
    : Behaviour(id, e)
    , _strength(data.at("_strength").at("Value"))
    , _color(data.at("_color").at("Value"))
{}


