// THIS CODE IS GENERATED BY REI ENGINE
// ANY CHANGES TO THIS FILE WILL BE LOST

#include <Modules/EntityManagement/EntityManager.h>
#include <Modules/Behaviour/Behaviour.h>
#include <Modules/Assets/AssetRefUtils.h>

#include "C:\Repos\Rei\Rei\src\Common\Math\Vector3.h"
#include "C:\Repos\Rei\Rei\src\Modules\Assets\AssetRef.h"
#include "C:\Repos\Rei\Rei\src\Modules\Physics\ModelCollider.h"
#include "C:\Repos\Rei\Rei\src\Modules\Physics\SphereCollider.h"
#include "C:\Repos\Rei\Rei\src\Modules\Render\Color\Color.h"
#include "C:\Repos\Rei Projects\New Project\New Project\Project\Scripts\Scripts\ColorLerp.h"
#include "C:\Repos\Rei\ReiSandbox\Scripts\RotateAroundAxis.h"
#include "C:\Repos\Rei Projects\New Project\New Project\Project\Scripts\Scripts\TestMovement.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\MeshRenderer.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\transformation\Transform.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\camera\Camera.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\light\AmbientLight.h"
#include "C:\Repos\Rei\Rei\resources\rei_behaviours\render\light\PointLight.h"

void ConfigureComponentsFactory(rei::BehaviourRegistry& f)
{
    rei::assets::RegisterAutoAssignHandler<rei::render::Model>();
    rei::assets::RegisterAutoAssignHandler<rei::render::Material>();

    f.RegisterComponent<::ColorLerp>(6, [](const rei::ecs::Entity e) -> nlohmann::json
                                     {
                                         auto& b = rei::GetInternalWorld()->GetRegistry()->Get<::ColorLerp>(e);
                                         return b.REI_GET();
                                     }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                     {
                                         auto& b = rei::GetInternalWorld()->GetRegistry()->Get<::ColorLerp>(e);
                                         b.REI_SET(json);
                                         b.AfterREI_SET();
                                     });
    f.RegisterComponent<::RotateAroundAxis>(7, [](const rei::ecs::Entity e) -> nlohmann::json
                                            {
                                                auto& b = rei::GetInternalWorld()->GetRegistry()->Get<::RotateAroundAxis>(e);
                                                return b.REI_GET();
                                            }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                            {
                                                auto& b = rei::GetInternalWorld()->GetRegistry()->Get<::RotateAroundAxis>(e);
                                                b.REI_SET(json);
                                                b.AfterREI_SET();
                                            });
    f.RegisterComponent<::TestMovement>(5, [](const rei::ecs::Entity e) -> nlohmann::json
                                        {
                                            auto& b = rei::GetInternalWorld()->GetRegistry()->Get<::TestMovement>(e);
                                            return b.REI_GET();
                                        }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                        {
                                            auto& b = rei::GetInternalWorld()->GetRegistry()->Get<::TestMovement>(e);
                                            b.REI_SET(json);
                                            b.AfterREI_SET();
                                        });
    f.RegisterComponent<rei::render::MeshRenderer>(1, [](const rei::ecs::Entity e) -> nlohmann::json
                                                   {
                                                       auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::MeshRenderer>(e);
                                                       return b.REI_GET();
                                                   }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                                   {
                                                       auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::MeshRenderer>(e);
                                                       b.REI_SET(json);
                                                       b.AfterREI_SET();
                                                   }, [](const nlohmann::json& data, std::vector<rei::assets::AssetDependency>& outDependencies)
                                                   {
                                                       if (data.contains("_model"))
                                                       {
                                                           const auto& rawValue = data.at("_model");
                                                           const auto& assetRefValue = rawValue.contains("Value") ? rawValue.at("Value") : rawValue;
                                                           if (assetRefValue.contains("Id"))
                                                           {
                                                               const auto& rawId = assetRefValue.at("Id");
                                                               const auto& idValue = rawId.is_object() && rawId.contains("Value") ? rawId.at("Value") : rawId;
                                                               const std::string assetId = idValue.is_string() ? idValue.get<std::string>() : "";
                                                               if (!assetId.empty())
                                                               {
                                                                   outDependencies.push_back(rei::assets::CreateTypedAssetDependency<rei::render::Model>(assetId));
                                                               }
                                                           }
                                                       }

                                                       if (data.contains("_material"))
                                                       {
                                                           const auto& rawValue = data.at("_material");
                                                           const auto& assetRefValue = rawValue.contains("Value") ? rawValue.at("Value") : rawValue;
                                                           if (assetRefValue.contains("Id"))
                                                           {
                                                               const auto& rawId = assetRefValue.at("Id");
                                                               const auto& idValue = rawId.is_object() && rawId.contains("Value") ? rawId.at("Value") : rawId;
                                                               const std::string assetId = idValue.is_string() ? idValue.get<std::string>() : "";
                                                               if (!assetId.empty())
                                                               {
                                                                   outDependencies.push_back(rei::assets::CreateTypedAssetDependency<rei::render::Material>(assetId));
                                                               }
                                                           }
                                                       }
                                                   });
    f.RegisterComponent<rei::Transform>(2, [](const rei::ecs::Entity e) -> nlohmann::json
                                                        {
                                                            auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::Transform>(e);
                                                            return b.REI_GET();
                                                        }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                                        {
                                                            auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::Transform>(e);
                                                            b.REI_SET(json);
                                                            b.AfterREI_SET();
                                                        });
    f.RegisterComponent<rei::render::Camera>(8, [](const rei::ecs::Entity e) -> nlohmann::json
                                             {
                                                 auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::Camera>(e);
                                                 return b.REI_GET();
                                             }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                             {
                                                 auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::Camera>(e);
                                                 b.REI_SET(json);
                                                 b.AfterREI_SET();
                                             });
    f.RegisterComponent<rei::render::AmbientLight>(3, [](const rei::ecs::Entity e) -> nlohmann::json
                                                   {
                                                       auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::AmbientLight>(e);
                                                       return b.REI_GET();
                                                   }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                                   {
                                                       auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::AmbientLight>(e);
                                                       b.REI_SET(json);
                                                       b.AfterREI_SET();
                                                   });
    f.RegisterComponent<rei::render::PointLight>(4, [](const rei::ecs::Entity e) -> nlohmann::json
                                                 {
                                                     auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::PointLight>(e);
                                                     return b.REI_GET();
                                                 }, [](const rei::ecs::Entity e, const nlohmann::json& json)
                                                 {
                                                     auto& b = rei::GetInternalWorld()->GetRegistry()->Get<rei::render::PointLight>(e);
                                                     b.REI_SET(json);
                                                     b.AfterREI_SET();
                                                 });
}

// --- REI_GET METHODS ---

nlohmann::json rei::math::Vector3::REI_GET() const
{
    return {
        {"REI_TYPE", "Vector3"},
        {"x", x},
        {"y", y},
        {"z", z},
    };
}

template <typename T>
nlohmann::json rei::assets::AssetRef<T>::REI_GET() const
{
    return {
        {"REI_TYPE", "AssetRef"},
        {"Id", Id},
    };
}

nlohmann::json rei::physics::ModelCollider::REI_GET() const
{
    return {
        {"REI_TYPE", "MeshCollider"},
    };
}

nlohmann::json rei::physics::SphereCollider::REI_GET() const
{
    return {
        {"REI_TYPE", "SphereCollider"},
        {"_radius", _radius},
    };
}

nlohmann::json rei::render::Color::REI_GET() const
{
    return {
        {"REI_TYPE", "Color"},
        {"r", r},
        {"g", g},
        {"b", b},
        {"a", a},
    };
}

nlohmann::json ColorLerp::REI_GET() const
{
    return {
        {"REI_TYPE", "ColorLerp"},
        {"_targetLightId", _targetLightId},
        {"_from", _from.REI_GET()},
        {"_to", _to.REI_GET()},
        {"_speed", _speed},
    };
}

nlohmann::json RotateAroundAxis::REI_GET() const
{
    return {
        {"REI_TYPE", "RotateAroundAxis"},
        {"_rotationSpeed", _rotationSpeed.REI_GET()},
    };
}

nlohmann::json TestMovement::REI_GET() const
{
    return {
        {"REI_TYPE", "TestMovement"},
        {"_radius", _radius},
        {"_speed", _speed},
        {"_horizontalMovement", _horizontalMovement},
    };
}

nlohmann::json rei::render::MeshRenderer::REI_GET() const
{
    return {
        {"REI_TYPE", "MeshRenderer"},
        {"_model", _model.REI_GET()},
        {"_material", _material.REI_GET()},
    };
}

nlohmann::json rei::Transform::REI_GET() const
{
    return {
        {"REI_TYPE", "Transform"},
        {"_position", _position.REI_GET()},
        {"_rotation", _rotation.REI_GET()},
        {"_scale", _scale.REI_GET()},
        {"_parent", _parent},
        {"_order", _order},
    };
}

nlohmann::json rei::render::Camera::REI_GET() const
{
    return {
        {"REI_TYPE", "Camera"},
        {"_fov", _fov},
        {"_orthographicSize", _orthographicSize},
        {"_nearClipPlane", _nearClipPlane},
        {"_farClipPlane", _farClipPlane},
        {"_backgroundColor", _backgroundColor.REI_GET()},
        {"_perspective", (int)_perspective},
    };
}

nlohmann::json rei::render::AmbientLight::REI_GET() const
{
    return {
        {"REI_TYPE", "AmbientLight"},
        {"_strength", _strength},
        {"_color", _color.REI_GET()},
    };
}

nlohmann::json rei::render::PointLight::REI_GET() const
{
    return {
        {"REI_TYPE", "PointLight"},
        {"_strength", _strength},
        {"_color", _color.REI_GET()},
    };
}


// --- REI_SET METHODS ---

void rei::math::Vector3::REI_SET(const nlohmann::json& data)
{
    if (data.contains("x")) x = data.at("x").at("Value");
    if (data.contains("y")) y = data.at("y").at("Value");
    if (data.contains("z")) z = data.at("z").at("Value");
}

template <typename T>
void rei::assets::AssetRef<T>::REI_SET(const nlohmann::json& data)
{
    if (data.contains("Id")) Id = data.at("Id").at("Value");
}

void rei::physics::ModelCollider::REI_SET(const nlohmann::json& data)
{
}

void rei::physics::SphereCollider::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_radius")) _radius = data.at("_radius").at("Value");
}

void rei::render::Color::REI_SET(const nlohmann::json& data)
{
    if (data.contains("r")) r = data.at("r").at("Value");
    if (data.contains("g")) g = data.at("g").at("Value");
    if (data.contains("b")) b = data.at("b").at("Value");
    if (data.contains("a")) a = data.at("a").at("Value");
}

void ColorLerp::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_targetLightId")) _targetLightId = data.at("_targetLightId").at("Value");
    if (data.contains("_from")) _from.REI_SET(data.at("_from").at("Value"));
    if (data.contains("_to")) _to.REI_SET(data.at("_to").at("Value"));
    if (data.contains("_speed")) _speed = data.at("_speed").at("Value");
}

void RotateAroundAxis::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_rotationSpeed")) _rotationSpeed.REI_SET(data.at("_rotationSpeed").at("Value"));
}

void TestMovement::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_radius")) _radius = data.at("_radius").at("Value");
    if (data.contains("_speed")) _speed = data.at("_speed").at("Value");
    if (data.contains("_horizontalMovement")) _horizontalMovement = data.at("_horizontalMovement").at("Value");
}

void rei::render::MeshRenderer::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_model")) _model.REI_SET(data.at("_model").at("Value"));
    if (data.contains("_model")) rei::assets::SyncAfterExternalChange(_model);
    if (data.contains("_material")) _material.REI_SET(data.at("_material").at("Value"));
    if (data.contains("_material")) rei::assets::SyncAfterExternalChange(_material);
}

void rei::Transform::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_position")) _position.REI_SET(data.at("_position").at("Value"));
    if (data.contains("_rotation")) _rotation.REI_SET(data.at("_rotation").at("Value"));
    if (data.contains("_scale")) _scale.REI_SET(data.at("_scale").at("Value"));
    if (data.contains("_parent")) _parent = data.at("_parent").at("Value");
    if (data.contains("_order")) _order = data.at("_order").at("Value");
}

void rei::render::Camera::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_fov")) _fov = data.at("_fov").at("Value");
    if (data.contains("_orthographicSize")) _orthographicSize = data.at("_orthographicSize").at("Value");
    if (data.contains("_nearClipPlane")) _nearClipPlane = data.at("_nearClipPlane").at("Value");
    if (data.contains("_farClipPlane")) _farClipPlane = data.at("_farClipPlane").at("Value");
    if (data.contains("_backgroundColor")) _backgroundColor.REI_SET(data.at("_backgroundColor").at("Value"));
    if (data.contains("_perspective")) _perspective = data.at("_perspective").at("Value");
}

void rei::render::AmbientLight::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_strength")) _strength = data.at("_strength").at("Value");
    if (data.contains("_color")) _color.REI_SET(data.at("_color").at("Value"));
}

void rei::render::PointLight::REI_SET(const nlohmann::json& data)
{
    if (data.contains("_strength")) _strength = data.at("_strength").at("Value");
    if (data.contains("_color")) _color.REI_SET(data.at("_color").at("Value"));
}
