#pragma once

constexpr i32 ENGINE_UPDATE_ERROR_EXIT_CODE = -3;
constexpr i32 ENGINE_INITIALIZATION_ERROR_EXIT_CODE = -2;
constexpr i32 DEFAULT_ERROR_EXIT_CODE = -1;
constexpr i32 DEFAULT_EXIT_CODE = 0;
constexpr i32 MAIN_WINDOW_CLOSED_EXIT_CODE = 1;
